### ISSUE TITLE
Starting error: No available configurations for the given RGBA pixel format

### ISSUE THREAD

**Issue by workingCPU** [pieces-app/support#565]
### Software

Pieces OS, VS Code

### Operating System / Platform

Linux

### Your Pieces OS Version

11.0.3

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Whenever I am trying to start Pieces OS or Pieces For Developers via the Linux Terminal, or via VS Code Plug-In (I don't use / haven't tried other ways), the following error message appears:

![Image](https://github.com/user-attachments/assets/3b7cc5de-7fdd-4a36-99f2-c806a7e540d6)

Information about my system:

```
inxi -G
Graphics:
  Device-1: NVIDIA GP107 [GeForce GTX 1050 Ti] driver: nvidia v: 535.183.01
  Display: x11 server: X.Org v: 1.21.1.7 with: Xwayland v: 22.1.9 driver: X:
    loaded: nvidia unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia
    resolution: 1680x1050~60Hz
  API: OpenGL v: 4.6.0 NVIDIA 535.183.01 renderer: NVIDIA GeForce GTX 1050
    Ti/PCIe/SSE2
```

```
uname -a
Linux debian 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux
```

Thanks in a advance!
